[build]
  command = "npm install --force && npm run build" # این خط تغییر کرده است
  publish = "build"
  environment = { NODE_VERSION = "18", NODE_OPTIONS = "--openssl-legacy-provider" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
